//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public static class FbxEuler {  
  // virtual void Dispose()  { } 

  public enum EOrder {
    eOrderXYZ,
    eOrderXZY,
    eOrderYZX,
    eOrderYXZ,
    eOrderZXY,
    eOrderZYX,
    eOrderSphericXYZ
  }

}

}
