//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Autodesk.Fbx {

public class FbxGeometryConverter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxGeometryConverter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxGeometryConverter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxGeometryConverter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativeMethods.delete_FbxGeometryConverter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool ComputeEdgeSmoothingFromNormals(FbxMesh pMesh) {
    bool ret = NativeMethods.FbxGeometryConverter_ComputeEdgeSmoothingFromNormals(swigCPtr, FbxMesh.getCPtr(pMesh));
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ComputePolygonSmoothingFromEdgeSmoothing(FbxMesh pMesh, int pIndex) {
    bool ret = NativeMethods.FbxGeometryConverter_ComputePolygonSmoothingFromEdgeSmoothing__SWIG_0(swigCPtr, FbxMesh.getCPtr(pMesh), pIndex);
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ComputePolygonSmoothingFromEdgeSmoothing(FbxMesh pMesh) {
    bool ret = NativeMethods.FbxGeometryConverter_ComputePolygonSmoothingFromEdgeSmoothing__SWIG_1(swigCPtr, FbxMesh.getCPtr(pMesh));
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxGeometryConverter(FbxManager pManager) : this(NativeMethods.new_FbxGeometryConverter(FbxManager.getCPtr(pManager)), true) {
    if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
  }

}

}
